// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Models;

[Table("Topic")]
public partial class Topic
{
    [Key]
    [Column("TopicID")]
    public int TopicId { get; set; }

    [Required]
    [StringLength(100)]
    public string TopicTitle { get; set; }

    [InverseProperty("Topic")]
    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}