// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Models;

[PrimaryKey("ExamId", "QuestionId")]
[Table("Answer")]
public partial class Answer
{
    [Key]
    [Column("ExamID")]
    public int ExamId { get; set; }

    [Column("StudentID")]
    public int? StudentId { get; set; }

    [Key]
    [Column("QuestionID")]
    public int QuestionId { get; set; }

    [Column("Answer")]
    public int? Answer1 { get; set; }

    [ForeignKey("Answer1")]
    [InverseProperty("Answers")]
    public virtual Choice Answer1Navigation { get; set; }

    [ForeignKey("ExamId")]
    [InverseProperty("Answers")]
    public virtual Exam Exam { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Answers")]
    public virtual Question Question { get; set; }

    [ForeignKey("StudentId")]
    [InverseProperty("Answers")]
    public virtual Student Student { get; set; }
}