// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Models
{
    public partial class GetExamReportWithModelAnswerResult
    {
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public string StudentAnswer { get; set; }
        public string ModelAnswer { get; set; }
    }
}
