// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Models;

public partial class Login
{
    public string Email { get; set; }

    public string Password { get; set; }
}