// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Models;

[Table("Question")]
public partial class Question
{
    [Key]
    [Column("QuestionID")]
    public int QuestionId { get; set; }

    [Required]
    [StringLength(500)]
    public string QuestionText { get; set; }

    [Required]
    [StringLength(20)]
    public string QuestionType { get; set; }

    [Required]
    [StringLength(20)]
    public string Complexity { get; set; }

    [Column("CourseID")]
    public int CourseId { get; set; }

    [InverseProperty("Question")]
    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    [InverseProperty("Question")]
    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    [ForeignKey("CourseId")]
    [InverseProperty("Questions")]
    public virtual Course Course { get; set; }

    [ForeignKey("QuestionId")]
    [InverseProperty("Questions")]
    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}