// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ExaminationSystem.StoredProcedure;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ExaminationSystem.Context
{
    public partial class ExaminationSystemContext
    {
        private IExaminationSystemContextProcedures _procedures;

        public virtual IExaminationSystemContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ExaminationSystemContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IExaminationSystemContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<GetTopicsByCourseResult>().HasNoKey().ToView(null);
        }
    }

    public partial class ExaminationSystemContextProcedures : IExaminationSystemContextProcedures
    {
        private readonly ExaminationSystemContext _context;

        public ExaminationSystemContextProcedures(ExaminationSystemContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetTopicsByCourseResult>> GetTopicsByCourseAsync(int? Course_ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Course_ID",
                    Value = Course_ID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetTopicsByCourseResult>("EXEC @returnValue = [dbo].[GetTopicsByCourse] @Course_ID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
