// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Model;

public partial class Instructor
{
    public int InstructorId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly HireDate { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public int DepartmentId { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}