// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Model;

public partial class Question
{
    public int QuestionId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public string Complexity { get; set; }

    public int CourseId { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual Course Course { get; set; }

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();
}