// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Model
{
    public partial class SelectALLChoiceResult
    {
        public int ChoiceID { get; set; }
        public string ChoiceText { get; set; }
        public bool IsCorrect { get; set; }
        public int QuestionID { get; set; }
    }
}
