// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Model
{
    public partial class SelectALLTeachResult
    {
        public int CourseID { get; set; }
        public int InstructorID { get; set; }
    }
}
