// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ExaminationSystem.Models;

public partial class Grade
{
    public int ExamId { get; set; }

    public int? StudentId { get; set; }

    public int Score { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Student Student { get; set; }
}