// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Models
{
    public partial class SelectALLTopicResult
    {
        public int TopicID { get; set; }
        public string TopicTitle { get; set; }
    }
}
