// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ExaminationSystem.Models;
using ExaminationSystem.StoredProcedure;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Context;

public partial class ExaminationSystemContext : DbContext
{
    public ExaminationSystemContext()
    {
    }

    public ExaminationSystemContext(DbContextOptions<ExaminationSystemContext> options)
        : base(options)
    {
    }
    public virtual DbSet<Answer> Answers { get; set; }

    public virtual DbSet<Choice> Choices { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Grade> Grades { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Student> Students { get; set; }

<<<<<<< HEAD
	public virtual DbSet<Student> Students { get; set; }

	public virtual DbSet<Topic> Topics { get; set; }
    public virtual DbSet<StudentGradeResult> StudentGradeResult{ get; set; }
    public virtual DbSet<ExamAnsModel> ExamAnsModel { get; set; }
    partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<StudentGradeResult>(entity =>
            entity.HasNoKey());
        modelBuilder.Entity<ExamAnsModel>(entity =>
           entity.HasNoKey());
    }
    public IEnumerable<StudentGradeResult>
    SP_GetStudentGrades(int id)
    {
        return this.StudentGradeResult
            .FromSqlInterpolated($"[dbo].[GetStudentGrades] {id}")
            .ToArray();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
=======
    public virtual DbSet<Topic> Topics { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
>>>>>>> 79e27462d310e8e001baf81a5e76ccf20c9f653a
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=ExaminationSystem;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}